# ./docker-compose.dev.yml
services:
  # 覆盖 env_file → 指向 development
  db:
    env_file:
      - ./env/api.env.development

  api:
    env_file:
      - ./env/api.env.development
    environment:
      FAST_REFRESH: 'true'

  server:
    env_file:
      - ./env/server.env.development
    environment:
      DEBUG: 'true'

  client:
    env_file:
      - ./env/client.env.development
    environment:
      REACT_APP_ENDPOINT_DEV: 'http://localhost:8000'
