name: block-web3-to-main

on:
  pull_request:
    branches: [main]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fail if web3 paths touched
        run: |
          DIFF=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..HEAD)
          echo "$DIFF" | grep -E '^web3/|^contract/' && {
            echo "::error ::Web3-related paths detected in PR to main – blocked."
            exit 1
          } || echo "No forbidden paths, continuing."
